### ISSUE TITLE
Where are the downloads?

### ISSUE THREAD

**Issue by CanAdam1609** [saptarshimondal/Comics-Manga-Downloader-Extension#13]
So, I try to download the comic, which works, and I click Direct Download, than, I check some places, like Downloads, Documents, etc. but I can't find it anywhere. What should I do?

**Comment by saptarshimondal** [comment]
@CanAdam1609  If you have selected "Direct Download" and clicked on "Download" button, it will be downloaded into your default Downloads folder. If it does not starts downloading, you can select "Built-In Browser" and click on "Download" button. Then you can save it as PDF file. If it does not work, please provide the website URL (from where you are downloading) and your browser.
